title: Harsh Vaishnav.  

logo: ProfilePic.jpg

description: Full Stack Developer - Python Developer

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag

#google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk"

email: harshvaishnav7295@gmail.com
